
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-database
    logging:
      driver: json-file
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - rs-network
    volumes:
      - database:/var/lib/mysql

  jenkins_node:
    image: luised160/s107-jenkins-node:TAG
    container_name: jenkins
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
     - 3333:3333
    # volumes:
    #   - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - rs-network

  redis:
    image: bitnami/redis
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - rs-network

networks:
  rs-network:
    driver: bridge

volumes:
  database: